Removed reference to FOSSA in README.md
temporalio/dashboards pull request #20
Opened 2022-03-31 20:42 UTC by mcbryde

## What was changed
Removed references to FOSSA

## Why?
FOSSA is being decommissioned.

2022-05-11 12:47 UTC, robholland requested changes

2022-05-11 12:47 UTC, robholland commented on README.md
> +[![FOSSA Status](https://app.fossa.com/api/projects/git%2Bgithub.com%2Ftemporalio%2Ftemporal-dashboards.svg?type=large)](https://app.fossa.com/projects/git%2Bgithub.com%2Ftemporalio%2Ftemporal-dashbo
I think this second block should go also?

2022-07-26 01:57 UTC, lorensr approved these changes

2022-07-26 08:51 UTC, robholland approved these changes

2022-07-26 08:51 UTC, merged